// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Invert.StateMachine;


public class EnemyStateAIBase : Invert.StateMachine.StateMachine {
    
    public EnemyStateAIBase(ViewModel vm, string propertyName) : 
            base(vm, propertyName) {
    }
    
    public override void Compose(List<State> states) {
        base.Compose(states);
    }
}
