// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrame.ExampleProject {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.Serialization;
    using UnityEngine;
    using UniRx;
    using uFrame.ExampleProject;
    
    
    public partial class UserViewModelBase : uFrame.MVVM.ViewModel {
        
        private P<AuthorizationState> _AuthorizationStateProperty;
        
        public UserViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
        
        public virtual P<AuthorizationState> AuthorizationStateProperty {
            get {
                return _AuthorizationStateProperty;
            }
            set {
                _AuthorizationStateProperty = value;
            }
        }
        
        public virtual AuthorizationState AuthorizationState {
            get {
                return AuthorizationStateProperty.Value;
            }
            set {
                AuthorizationStateProperty.Value = value;
            }
        }
        
        public override void Bind() {
            base.Bind();
            _AuthorizationStateProperty = new P<AuthorizationState>(this, "AuthorizationState");
        }
        
        public override void Read(ISerializerStream stream) {
            base.Read(stream);
            this.AuthorizationState = (AuthorizationState)stream.DeserializeInt("AuthorizationState");;
        }
        
        public override void Write(ISerializerStream stream) {
            base.Write(stream);
            stream.SerializeInt("AuthorizationState", (int)this.AuthorizationState);;
        }
        
        protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
            base.FillCommands(list);
        }
        
        protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
            base.FillProperties(list);
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_AuthorizationStateProperty, false, false, true, false));
        }
    }
    
    public partial class UserViewModel {
        
        public UserViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
                base(aggregator) {
        }
    }
}
