// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Linq;


[DiagramInfoAttribute("SimpleBinding")]
public partial class GameElementViewModel : ViewModel {
    
    public readonly P<PlayerElementViewModel> _PlayerProperty = new P<PlayerElementViewModel>();
    
    public virtual PlayerElementViewModel Player {
        get {
            return _PlayerProperty.Value;
        }
        set {
            _PlayerProperty.Value = value;
        }
    }
}

[DiagramInfoAttribute("SimpleBinding")]
public partial class PlayerElementViewModel : ViewModel {
}
