// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TargetingDemo.PlaymakerActions {
    using System;
    using System.Collections;
    using System.Linq;
    using UnityEngine;
    using HutongGames.PlayMaker;
    
    
    public class RegeneratePlaymakerActionBase : FsmStateAction {
    }
    
    public class FirePlaymakerActionBase : FsmStateAction {
    }
}
