// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Linq;


[DiagramInfoAttribute("TargetingDemo")]
public partial class TargetingGameElementViewModel : ViewModel {
    
    public readonly P<System.String> _PlayerProperty = new P<string>();
    
    public virtual string Player {
        get {
            return _PlayerProperty.Value;
        }
        set {
            _PlayerProperty.Value = value;
        }
    }
}

[DiagramInfoAttribute("TargetingDemo")]
public partial class TargetableViewModel : ViewModel {
    
    public readonly P<System.String> _HealthProperty = new P<string>();
    
    private ICommand _Regenerate;
    
    public virtual string Health {
        get {
            return _HealthProperty.Value;
        }
        set {
            _HealthProperty.Value = value;
        }
    }
    
    public virtual ICommand Regenerate {
        get {
            return _Regenerate;
        }
        set {
            _Regenerate = value;
        }
    }
}

[DiagramInfoAttribute("TargetingDemo")]
public partial class PlayerViewModel : ViewModel {
    
    public readonly P<TargetableViewModel> _CurrentTargetProperty = new P<TargetableViewModel>();
    
    private ICommand _Fire;
    
    public virtual TargetableViewModel CurrentTarget {
        get {
            return _CurrentTargetProperty.Value;
        }
        set {
            _CurrentTargetProperty.Value = value;
        }
    }
    
    public virtual ICommand Fire {
        get {
            return _Fire;
        }
        set {
            _Fire = value;
        }
    }
}

[DiagramInfoAttribute("TargetingDemo")]
public partial class CubeViewModel : TargetableViewModel {
}

[DiagramInfoAttribute("TargetingDemo")]
public partial class CylinderViewModel : TargetableViewModel {
}
