// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrame.ExampleProject {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.Serialization;
    
    
    public partial class CloseCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class LoginCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class ApplyCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class DefaultCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class SelectLevelCommand : uFrame.MVVM.ViewModelCommand {
        
        private LevelDescriptor _Argument;
        
        public LevelDescriptor Argument {
            get {
                return _Argument;
            }
            set {
                _Argument = value;
            }
        }
    }
}
