// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Linq;
using UnityEngine;


[DiagramInfoAttribute("Checkers")]
public abstract class CheckerBoardViewBase : ViewBase {
    
    [UnityEngine.SerializeField()]
    private NewViewComponent _NewViewComponent;
    
    public override string DefaultIdentifier {
        get {
            return "CheckerBoard";
        }
    }
    
    public override System.Type ViewModelType {
        get {
            return typeof(CheckerBoardViewModel);
        }
    }
    
    public virtual NewViewComponent NewViewComponent {
        get {
            return _NewViewComponent ?? (_NewViewComponent = GetComponent<NewViewComponent>());
        }
        set {
            this._NewViewComponent = value;
        }
    }
    
    public override bool IsMultiInstance {
        get {
            return false;
        }
    }
    
    public CheckerBoardViewModel CheckerBoard {
        get {
            return ((CheckerBoardViewModel)(this.ViewModelObject));
        }
        set {
            this.ViewModelObject = value;
        }
    }
    
    public virtual void CheckersAdded(CheckerViewBase item) {
    }
    
    public virtual void CheckersRemoved(CheckerViewBase item) {
    }
    
    public virtual ViewBase CreateCheckersView(CheckerViewModel value) {
        return null;
    }
    
    public virtual void PlatesAdded(CheckerPlateViewBase item) {
    }
    
    public virtual void PlatesRemoved(CheckerPlateViewBase item) {
    }
    
    public virtual ViewBase CreatePlatesView(CheckerPlateViewModel value) {
        return null;
    }
    
    public override void Bind() {
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<CheckerBoardController>());
    }
    
    protected override void InitializeViewModel(ViewModel viewModel) {
    }
}

[DiagramInfoAttribute("Checkers")]
public abstract class CheckerMoveViewBase : ViewBase {
    
    public override string DefaultIdentifier {
        get {
            return "CheckerMove";
        }
    }
    
    public override System.Type ViewModelType {
        get {
            return typeof(CheckerMoveViewModel);
        }
    }
    
    public override bool IsMultiInstance {
        get {
            return true;
        }
    }
    
    public CheckerMoveViewModel CheckerMove {
        get {
            return ((CheckerMoveViewModel)(this.ViewModelObject));
        }
        set {
            this.ViewModelObject = value;
        }
    }
    
    public override void Bind() {
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<CheckerMoveController>());
    }
    
    protected override void InitializeViewModel(ViewModel viewModel) {
    }
}

[DiagramInfoAttribute("Checkers")]
public abstract class CheckerPlateViewBase : ViewBase {
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public bool _CanMoveTo;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public UnityEngine.Vector2 _Position;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public bool _IsEven;
    
    public override string DefaultIdentifier {
        get {
            return "CheckerPlate";
        }
    }
    
    public override System.Type ViewModelType {
        get {
            return typeof(CheckerPlateViewModel);
        }
    }
    
    public override bool IsMultiInstance {
        get {
            return true;
        }
    }
    
    public CheckerPlateViewModel CheckerPlate {
        get {
            return ((CheckerPlateViewModel)(this.ViewModelObject));
        }
        set {
            this.ViewModelObject = value;
        }
    }
    
    public virtual void CanMoveToChanged(bool value) {
    }
    
    public virtual void PositionChanged(UnityEngine.Vector2 value) {
    }
    
    public virtual void IsEvenChanged(bool value) {
    }
    
    public override void Bind() {
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<CheckerPlateController>());
    }
    
    public virtual void ExecuteSelectCommand() {
        this.ExecuteCommand(CheckerPlate.SelectCommand);
    }
    
    protected override void InitializeViewModel(ViewModel viewModel) {
        CheckerPlateViewModel checkerPlate = ((CheckerPlateViewModel)(viewModel));
        checkerPlate.CanMoveTo = this._CanMoveTo;
        checkerPlate.Position = this._Position;
        checkerPlate.IsEven = this._IsEven;
    }
}

[DiagramInfoAttribute("Checkers")]
public abstract class CheckersGameViewBase : ViewBase {
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public int _BlackScore;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public int _RedScore;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public ViewBase _Board;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public ViewBase _CurrentChecker;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public CheckerType _CurrentPlayer;
    
    public override string DefaultIdentifier {
        get {
            return "CheckersGame";
        }
    }
    
    public override System.Type ViewModelType {
        get {
            return typeof(CheckersGameViewModel);
        }
    }
    
    public override bool IsMultiInstance {
        get {
            return false;
        }
    }
    
    public CheckersGameViewModel CheckersGame {
        get {
            return ((CheckersGameViewModel)(this.ViewModelObject));
        }
        set {
            this.ViewModelObject = value;
        }
    }
    
    public virtual void BlackScoreChanged(int value) {
    }
    
    public virtual void RedScoreChanged(int value) {
    }
    
    public virtual void BoardChanged(CheckerBoardViewModel value) {
    }
    
    public virtual void CurrentCheckerChanged(CheckerViewModel value) {
    }
    
    public virtual void CurrentPlayerChanged(CheckerType value) {
    }
    
    public virtual void AllowedMovesAdded(CheckerMoveViewBase item) {
    }
    
    public virtual void AllowedMovesRemoved(CheckerMoveViewBase item) {
    }
    
    public virtual ViewBase CreateAllowedMovesView(CheckerMoveViewModel value) {
        return null;
    }
    
    public override void Bind() {
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<CheckersGameController>());
    }
    
    public virtual void ExecuteGameOver() {
        this.ExecuteCommand(CheckersGame.GameOver);
    }
    
    protected override void InitializeViewModel(ViewModel viewModel) {
        CheckersGameViewModel checkersGame = ((CheckersGameViewModel)(viewModel));
        checkersGame.BlackScore = this._BlackScore;
        checkersGame.RedScore = this._RedScore;
        checkersGame.Board = this._Board == null ? null : this._Board.ViewModelObject as CheckerBoardViewModel;
        checkersGame.CurrentChecker = this._CurrentChecker == null ? null : this._CurrentChecker.ViewModelObject as CheckerViewModel;
        checkersGame.CurrentPlayer = this._CurrentPlayer;
    }
}

[DiagramInfoAttribute("Checkers")]
public abstract class CheckerViewBase : ViewBase {
    
    [UnityEngine.SerializeField()]
    private KingMeStrategy _KingMeStrategy;
    
    [UnityEngine.SerializeField()]
    private ContiniousRotation _ContiniousRotation;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public bool _IsKingMe;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public UnityEngine.Vector2 _Position;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public bool _Selected;
    
    [UFGroup("View Model Properties")]
    [UnityEngine.HideInInspector()]
    public CheckerType _Type;
    
    public override string DefaultIdentifier {
        get {
            return "Checker";
        }
    }
    
    public override System.Type ViewModelType {
        get {
            return typeof(CheckerViewModel);
        }
    }
    
    public virtual KingMeStrategy KingMeStrategy {
        get {
            return _KingMeStrategy ?? (_KingMeStrategy = GetComponent<KingMeStrategy>());
        }
        set {
            this._KingMeStrategy = value;
        }
    }
    
    public virtual ContiniousRotation ContiniousRotation {
        get {
            return _ContiniousRotation ?? (_ContiniousRotation = GetComponent<ContiniousRotation>());
        }
        set {
            this._ContiniousRotation = value;
        }
    }
    
    public override bool IsMultiInstance {
        get {
            return true;
        }
    }
    
    public CheckerViewModel Checker {
        get {
            return ((CheckerViewModel)(this.ViewModelObject));
        }
        set {
            this.ViewModelObject = value;
        }
    }
    
    public virtual void IsKingMeChanged(bool value) {
    }
    
    public virtual void PositionChanged(UnityEngine.Vector2 value) {
    }
    
    public virtual void SelectedChanged(bool value) {
    }
    
    public virtual void TypeChanged(CheckerType value) {
    }
    
    public override void Bind() {
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<CheckerController>());
    }
    
    public virtual void ExecuteSelectCommand() {
        this.ExecuteCommand(Checker.SelectCommand);
    }
    
    protected override void InitializeViewModel(ViewModel viewModel) {
        CheckerViewModel checker = ((CheckerViewModel)(viewModel));
        checker.IsKingMe = this._IsKingMe;
        checker.Position = this._Position;
        checker.Selected = this._Selected;
        checker.Type = this._Type;
    }
}

[DiagramInfoAttribute("Checkers")]
public abstract class AICheckersGameViewBase : CheckersGameViewBase {
    
    public override System.Type ViewModelType {
        get {
            return typeof(AICheckersGameViewModel);
        }
    }
    
    public override bool IsMultiInstance {
        get {
            return false;
        }
    }
    
    public AICheckersGameViewModel AICheckersGame {
        get {
            return ((AICheckersGameViewModel)(this.ViewModelObject));
        }
        set {
            this.ViewModelObject = value;
        }
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<AICheckersGameController>());
    }
    
    protected override void InitializeViewModel(ViewModel viewModel) {
        base.InitializeViewModel(viewModel);
    }
}

[DiagramInfoAttribute("Checkers")]
public abstract class MainMenuViewBase : ViewBase {
    
    public override string DefaultIdentifier {
        get {
            return "MainMenu";
        }
    }
    
    public override System.Type ViewModelType {
        get {
            return typeof(MainMenuViewModel);
        }
    }
    
    public override bool IsMultiInstance {
        get {
            return false;
        }
    }
    
    public MainMenuViewModel MainMenu {
        get {
            return ((MainMenuViewModel)(this.ViewModelObject));
        }
        set {
            this.ViewModelObject = value;
        }
    }
    
    public override void Bind() {
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<MainMenuController>());
    }
    
    public virtual void ExecutePlay() {
        this.ExecuteCommand(MainMenu.Play);
    }
    
    protected override void InitializeViewModel(ViewModel viewModel) {
    }
}

public partial class CheckerPlateView : CheckerPlateViewBase {
    
    protected override void Apply() {
        base.Apply();
        CheckerPlate.Dirty = false;
    }
    
    protected override void PreBind() {
        base.PreBind();
    }
}

public partial class CheckerBoardView : CheckerBoardViewBase {
    
    [UFToggleGroup("Checkers")]
    [UnityEngine.HideInInspector()]
    public bool _BindCheckers = true;
    
    [UnityEngine.HideInInspector()]
    public System.Collections.Generic.List<CheckerViewBase> _CheckersList;
    
    [UFGroup("Checkers")]
    [UnityEngine.HideInInspector()]
    public bool _CheckersSceneFirst;
    
    [UFGroup("Checkers")]
    [UnityEngine.HideInInspector()]
    public UnityEngine.Transform _CheckersContainer;
    
    [UFToggleGroup("Plates")]
    [UnityEngine.HideInInspector()]
    public bool _BindPlates = true;
    
    [UnityEngine.HideInInspector()]
    public System.Collections.Generic.List<CheckerPlateViewBase> _PlatesList;
    
    [UFGroup("Plates")]
    [UnityEngine.HideInInspector()]
    public bool _PlatesSceneFirst;
    
    [UFGroup("Plates")]
    [UnityEngine.HideInInspector()]
    public UnityEngine.Transform _PlatesContainer;
    
    protected override void Apply() {
        base.Apply();
        CheckerBoard.Dirty = false;
    }
    
    protected override void PreBind() {
        base.PreBind();
        if (this._BindCheckers) {
            var binding = this.BindToViewCollection(() => CheckerBoard._CheckersProperty);
            if ((_CheckersContainer == null)) {
            }
            else {
                binding.SetParent(_CheckersContainer);
            }
            if (_CheckersSceneFirst) {
                binding.ViewFirst();
            }
            binding.SetAddHandler(item=>CheckersAdded(item as CheckerViewBase));
            binding.SetRemoveHandler(item=>CheckersRemoved(item as CheckerViewBase));
            binding.SetCreateHandler(viewModel=>{ return CreateCheckersView(viewModel as CheckerViewModel); }); ;
        }
        if (this._BindPlates) {
            var binding = this.BindToViewCollection(() => CheckerBoard._PlatesProperty);
            if ((_PlatesContainer == null)) {
            }
            else {
                binding.SetParent(_PlatesContainer);
            }
            if (_PlatesSceneFirst) {
                binding.ViewFirst();
            }
            binding.SetAddHandler(item=>PlatesAdded(item as CheckerPlateViewBase));
            binding.SetRemoveHandler(item=>PlatesRemoved(item as CheckerPlateViewBase));
            binding.SetCreateHandler(viewModel=>{ return CreatePlatesView(viewModel as CheckerPlateViewModel); }); ;
        }
    }
}

public partial class CheckerView : CheckerViewBase {
    
    protected override void Apply() {
        base.Apply();
        Checker.Dirty = false;
    }
    
    protected override void PreBind() {
        base.PreBind();
    }
}

public partial class CheckersGameView : CheckersGameViewBase {
    
    protected override void Apply() {
        base.Apply();
        CheckersGame.Dirty = false;
    }
    
    protected override void PreBind() {
        base.PreBind();
    }
}

public partial class CheckersHudView : CheckersGameViewBase {
    
    protected override void Apply() {
        base.Apply();
        CheckersGame.Dirty = false;
    }
    
    protected override void PreBind() {
        base.PreBind();
    }
}

public partial class MainMenuView : MainMenuViewBase {
    
    protected override void Apply() {
        base.Apply();
        MainMenu.Dirty = false;
    }
    
    protected override void PreBind() {
        base.PreBind();
    }
}

public partial class NewViewComponent : ViewComponent {
    
    public virtual CheckerBoardViewModel CheckerBoard {
        get {
            return ((CheckerBoardViewModel)(this.View.ViewModelObject));
        }
    }
}

public partial class NewViewComponent1 : NewViewComponent {
}

public partial class KingMeStrategy : ViewComponent {
    
    public virtual CheckerViewModel Checker {
        get {
            return ((CheckerViewModel)(this.View.ViewModelObject));
        }
    }
    
    public virtual void ExecuteSelectCommand() {
        this.View.ExecuteCommand(Checker.SelectCommand);
    }
}

public partial class DoubleUpKingMeStrategy : KingMeStrategy {
}

public partial class FlipOverKingMeStrategy : KingMeStrategy {
}

public partial class ContiniousRotation : ViewComponent {
    
    public virtual CheckerViewModel Checker {
        get {
            return ((CheckerViewModel)(this.View.ViewModelObject));
        }
    }
    
    public virtual void ExecuteSelectCommand() {
        this.View.ExecuteCommand(Checker.SelectCommand);
    }
}

public partial class MapView : ContiniousRotation {
}

public partial class PlayerScreenView : ContiniousRotation {
}
