// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Linq;


[DiagramInfoAttribute("MikeDemo")]
public partial class CubeGameViewModel : ViewModel {
    
    public readonly P<System.String> _BasePropertyProperty = new P<string>();
    
    public readonly ModelCollection<System.String> _CubesProperty = new ModelCollection<string>();
    
    private ICommand _EndGame;
    
    public virtual string BaseProperty {
        get {
            return _BasePropertyProperty.Value;
        }
        set {
            _BasePropertyProperty.Value = value;
        }
    }
    
    public virtual System.Collections.Generic.ICollection<string> Cubes {
        get {
            return _CubesProperty;
        }
        set {
            _CubesProperty.Value = value.ToList();
        }
    }
    
    public virtual ICommand EndGame {
        get {
            return _EndGame;
        }
        set {
            _EndGame = value;
        }
    }
}

[DiagramInfoAttribute("MikeDemo")]
public partial class CoolCubeGameViewModel : CubeGameViewModel {
    
    public readonly P<System.String> _DerivedPropertyProperty = new P<string>();
    
    private ICommand _Play;
    
    public virtual string DerivedProperty {
        get {
            return _DerivedPropertyProperty.Value;
        }
        set {
            _DerivedPropertyProperty.Value = value;
        }
    }
    
    public virtual ICommand Play {
        get {
            return _Play;
        }
        set {
            _Play = value;
        }
    }
}
