// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Linq;


[DiagramInfoAttribute("MikeDemo")]
public partial class CubeGameViewModel : ViewModel {
    
    public readonly ModelCollection<System.String> _CubesProperty = new ModelCollection<string>();
    
    public virtual System.Collections.Generic.ICollection<string> Cubes {
        get {
            return _CubesProperty;
        }
        set {
            _CubesProperty.Value = value.ToList();
        }
    }
}
