// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Linq;
using UnityEngine;


[DiagramInfoAttribute("MikeDemo")]
public abstract class CubeGameViewBase : ViewBase {
    
    [UFToggleGroup("Cubes")]
    [UnityEngine.HideInInspector()]
    public bool _BindCubes;
    
    public override System.Type ViewModelType {
        get {
            return typeof(CubeGameViewModel);
        }
    }
    
    public override bool IsMultiInstance {
        get {
            return false;
        }
    }
    
    public CubeGameViewModel CubeGame {
        get {
            return ((CubeGameViewModel)(this.ViewModelObject));
        }
        set {
            this.ViewModelObject = value;
        }
    }
    
    public virtual void CubesAdded(string item) {
    }
    
    public virtual void CubesRemoved(string item) {
    }
    
    public override void Bind() {
        if (this._BindCubes) {
            var binding = this.BindCollection(() => CubeGame._CubesProperty);
            binding.SetAddHandler(CubesAdded);
            binding.SetRemoveHandler(CubesRemoved);
        }
    }
    
    public override ViewModel CreateModel() {
        return this.RequestViewModel(GameManager.Container.Resolve<CubeGameController>());
    }
    
    protected override void InitializeViewModel(ViewModel viewModel) {
    }
}

public partial class CubeGameView : CubeGameViewBase {
}
