// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrame.DefaultProject {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UniRx;
    
    
    public partial class MainMenuScreenViewModelBase : ViewModel {
        
        private Signal<PlayGameCommand> _PlayGame;
        
        public MainMenuScreenViewModelBase(IEventAggregator aggregator) : 
                base(aggregator) {
        }
        
        public virtual Signal<PlayGameCommand> PlayGame {
            get {
                return _PlayGame;
            }
            set {
                _PlayGame = value;
            }
        }
        
        public override void Bind() {
            base.Bind();
            this.PlayGame = new Signal<PlayGameCommand>(this);
        }
        
        public override void Read(ISerializerStream stream) {
            base.Read(stream);
        }
        
        public override void Write(ISerializerStream stream) {
            base.Write(stream);
        }
        
        protected override void FillCommands(System.Collections.Generic.List<ViewModelCommandInfo> list) {
            base.FillCommands(list);
            list.Add(new ViewModelCommandInfo("PlayGame", PlayGame) { ParameterType = typeof(void) });
        }
        
        protected override void FillProperties(System.Collections.Generic.List<ViewModelPropertyInfo> list) {
            base.FillProperties(list);
        }
    }
    
    public partial class MainMenuScreenViewModel {
        
        public MainMenuScreenViewModel(IEventAggregator aggregator) : 
                base(aggregator) {
        }
    }
}
